# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://rick.gerk.in/
title: Rick Gerkin
email: rgerkin at gmail dot com
author: Richard C Gerkin
description: > # "Rick Gerkin's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/rgerkin
  - icon: flask
    title: scholar
    url: https://scholar.google.com/citations?user=GzG5kRAAAAAJ&hl=en
  - icon: github
    title: github
    url: https://github.com/rgerkin
  - icon: twitter
    title: twitter
    url: https://twitter.com/rgerkin
  - icon: file-pdf-o
    title: resume
    url: http://rick.gerk.in/cv
  - icon: envelope-o
    title: email
    url: mailto:rgerkin at gmail dot com